[features]
seeds = false
skip-lint = false

[programs.localnet]
soltix_registry = "EpkzAK8Q6MsUcLqXxBoJeat5FDRoRWeHxvShHV7nAoF8"
soltix_organization = "FckJnm69ZRMy84E6PGxzb8b1vBa9WMRw4E8EsjkJifr"
soltix_event = "6MLxi26fU4wWDh33NvEuoA3aWbasv1vTpwbktdLk368k"

[programs.devnet]
soltix_registry = "EpkzAK8Q6MsUcLqXxBoJeat5FDRoRWeHxvShHV7nAoF8"
soltix_organization = "FckJnm69ZRMy84E6PGxzb8b1vBa9WMRw4E8EsjkJifr"
soltix_event = "6MLxi26fU4wWDh33NvEuoA3aWbasv1vTpwbktdLk368k"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deploy = "node migrations/deploy.js"